server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  cloud:
    gateway:
      routes:
        - id: taxi-service-post
          uri: http://${TAXI_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/taxi
            - Method=POST
          filters:
            - SetPath=/api/taxi/create
        - id: taxi-service
          uri: http://${TAXI_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/taxi
            - Method=GET
          filters:
            - SetPath=/api/taxi
        - id: trip-service
          uri: http://${TRIP_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/trips
          filters:
            - SetPath=/api/trip