server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '1018395572599-t31o42m7rqm17so7oq30fd1jev6vmknv.apps.googleusercontent.com'
            client-secret: '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'
            scope:
              - openid
              - profile
              - email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: customer-service-get
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/customers
            - Method=GET
          filters:
            - SetPath=/api/customer
        - id: customer-service-post
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/customers/post
            - Method=POST
          filters:
            - SetPath=/api/customer
        - id: customer-service-put
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/customers/put
            - Method=PUT
          filters:
            - SetPath=/api/customer/{id}
        - id: taxi-service
          uri: http://${TAXI_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/taxi
            - Method=GET
          filters:
            - SetPath=/api/taxi
        - id: trip-service
          uri: http://${TRIP_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/trips
            - Method=GET
          filters:
            - SetPath=/api/trip