server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${{secrets.OAUTH_ID}}
            client-secret: ${{secrets.OAUTH_SECRET}}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwt-set-uri: https://www.googleapis.com/oath2/v3/certs
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/customers
            - Method=GET
          filters:
            - SetPath=/api/customer
        - id: taxi-service
          uri: http://${TAXI_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/taxi
            - Method=GET
          filters:
            - SetPath=/api/taxi
        - id: trip-service
          uri: http://${TRIP_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/trips
            - Method=GET
          filters:
            - SetPath=/api/trip