server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_ID}
            client-secret: ${OAUTH_SECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/customers
            - Method=GET
          filters:
            - SetPath=/api/customer
        - id: customer-service-post
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/customer/post
            - Method=POST
          filters:
            - SetPath=/api/customer
        - id: customer-service-put
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/customer/put/{id}
            - Method=PUT
          filters:
            - SetPath=/api/customer/{id}
        - id: customer-service-delete
          uri: http://${CUSTOMER_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/customer/delete/{id}
            - Method=DELETE
          filters:
            - SetPath=/api/customer/{id}
        - id: taxi-service-get
          uri: http://${TAXI_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/taxis
            - Method=GET
          filters:
            - SetPath=/api/taxi
        - id: taxi-service-post
          uri: http://${TAXI_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/taxi/post
            - Method=POST
          filters:
            - SetPath=/api/taxi
        - id: trip-service
          uri: http://${TRIP_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/trips
            - Method=GET
          filters:
            - SetPath=/api/trip